run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - gocyclo
    - goconst
    - whitespace
